services:
  api:
    build:
      context: .
      dockerfile: YellowHouseStudio.LifeOrbit.Api/Dockerfile
    container_name: lifeorbit-api
    ports:
      - "5050:80"
      - "5051:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=devdb;Username=devuser;Password=devpass
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "devuser", "-d", "devdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: